language: "python"
python:
  - "3.7.4"
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: test
      script: pycodestyle .
    - # stage name not required, will continue to use `test`
      script: pytest
